### ISSUE TITLE
ThunderboltIoC Runtime error with getting registered entities.

### ISSUE THREAD

**Issue by samarthshroff** [AlyElHaddad/ThunderboltIoc#4] opened 2022-05-12 18:16 UTC
Hi Aly,

I tried implementing thunder bolt ioc in a .net framework 4.8 (C# version 9.0) class library project in Visual Studio 2019 (16.11.13). It did compile but now I am getting a runtime error.
![image](https://user-images.githubusercontent.com/22641683/168140904-e7908692-b14e-4174-b9b4-fdfba32e2cc9.png)

I have registered this IDataManager like this
![image](https://user-images.githubusercontent.com/22641683/168140968-4dfc33fa-cc64-428d-bf94-07c63c2d3c44.png)

and am attaching this class like this in the main class constructor
![image](https://user-images.githubusercontent.com/22641683/168141056-7880a9ac-2efe-4b6d-aa92-b52a81bd2f81.png)

On debugging I found that 
`internal static void Register(in ThunderboltServiceLifetime serviceLifetime) => ThunderboltServiceRegistry<T>.RegisteredLifetime = serviceLifetime;`
function is called from ThunderboltContainer.AddTransient but again on calling the Get function it calls the 

Factory function of ThunderboltServiceRegistry`1.cs file which in turn tries to access dictatedFactory which is null and thus throws that error from the screenshot.

This is the build output from visual studio 
![image](https://user-images.githubusercontent.com/22641683/168141789-448c57cd-d270-4e4d-8981-7026a145ce38.png)

P.S. - this is the continuation of the other issue that I had posted a few days back - https://github.com/AlyElhaddad/ThunderboltIoc/issues/3

Also, request you to not close the issue if I don't reply within a couple of days.

**Comment by AlyElhaddad** [comment] 2022-05-13 06:25
To further diagnose this, please add the following two lines into your `PropertyGroup` section of your `*.csproj` file.

```
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GeneratedFiles</CompilerGeneratedFilesOutputPath>
```
Upon the successful build (and successful source generation), a new generated file should appear in the following path:
`[you project directory]\obj\GeneratedFiles\[generator assembly]\[generator class]\IoCRegistry.g.cs`

Would you please share the contents of that file?
Also, would you please share a copy of the sample project where the issue is reproduceable?

**Comment by samarthshroff** [comment] 2022-05-13 14:38
Thank you for the reply. The GeneratedFiles directory is empty. Also, I am attaching the sample project's zip file to this comment itself instead of a git link.

[ThunderBoltIoCSample.zip](https://github.com/AlyElhaddad/ThunderboltIoc/files/8688666/ThunderBoltIoCSample.zip)

Thank you

**Comment by AlyElhaddad** [comment] 2022-05-13 14:56
I have noticed from your sample that your project was referencing the package using the legacy `packages.config` format. I have switched your sample to use the `PackageReference` format instead, and it worked right away.

[ThunderBoltIoCSample - Switched to PackageReference.zip](https://github.com/AlyElhaddad/ThunderboltIoc/files/8688788/ThunderBoltIoCSample.-.Switched.to.PackageReference.zip)

Further read: [Migrate from packages.config to PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference)

**Comment by samarthshroff** [comment] 2022-05-16 18:15
Oh, so it won't work with the packages.config then? Asking because I may need that. But I will see if now that I am not using the other packages do I really need to use packages.config, if not then I will revert my actual project to PackageReference (as I moved to config file because I was facing some import issues with PackageReference).

Thank you!

**Comment by samarthshroff** [comment] 2022-05-16 18:29
Okay, so I opened the sample project that has Packagereference instead of package.config in Visual studio 2019 and restored nugets and built it.  The obj/Generated folder is still empty for me.

**Comment by AlyElhaddad** [comment] 2022-05-17 05:20
Yes, it appears it doesn't work with `packages.config`. Regarding not being able to find generated files, make sure you're checking in `ThunderBoltIoCSample\obj` and not in `ThunderboltIoCConsole\obj` in your sample. If -after a successful build- you still couldn't find anything, there's really nothing that  I can do about it as I'm unable to reproduce the problem here.

**Comment by samarthshroff** [comment] 2022-05-17 13:39
Yes, I checked the ThunerboltIoCSample\obj\Generated directory itself and it is empty. Maybe there is some setting or an installation (for thunderbolt code generation) that is present on your machine and am missing it.

**Comment by AlyElhaddad** [comment] 2022-05-17 15:46
There is none. May I suggest you download any sample from the samples directory and make sure that it works?

Also, have you tried running `dotnet build` in your project directory and checking whether any generated files appear?

**Comment by samarthshroff** [comment] 2022-05-19 18:20
Yes I did run that command but no files were generated. I will try a sample from the directory and will reply as soon as possible.

**Comment by AlyElhaddad** [comment] 2022-05-30 08:47
@samarthshroff it's been 10+ days since I last heard from you. I won't just leave an un-reproduceable issue open indefinitely. I'll close this one for now and should you have any further inquiries, please reply to this issue instead of opening a new one.

**Closed as completed** 2022-05-30 08:48 UTC
